name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      pull-requests: write
    steps:
      - name: NoLog or Breaking
        uses: mheap/github-action-required-labels@v5
        with:
          mode: maximum
          count: 1
          labels: |
            NoLog
            Breaking
      - name: Only one regular label
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            Add
            Change
            Fix
            Remove
